defaults: &defaults
  node_host: localhost:8000
  node_token: f54d6efbde3034508e37aa0df14c3d8fe0c1b506c

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  node_host: emerleite.no.de
